<?php

namespace AppBundle\Repository;

/**
 * CampaignsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAllCampaignsWithOrganization()
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT c.id as id, ' .
                                 'c.name as name, ' .
                                 'c.flightStartDate, ' .
                                 'c.flightEndDate, ' .
                                 'c.flightLength, ' .
                                 'o.name as orgName, ' .
                                 'r.name as regionName ' .
                          'FROM AppBundle:Campaigns c ' .
                              'JOIN AppBundle:Organizations o ' .
                                  'WITH c.organizationId = o.id ' .
                              'JOIN AppBundle:Regions r ' .
                                  'WITH c.regionId = r.id');
        $data = $query->getResult();

        return $data;
    }
}
