<?php

namespace AppBundle\Repository;

/**
 * OrganizationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationsRepository extends \Doctrine\ORM\EntityRepository
{
}
