<?php

namespace AppBundle\Repository;

/**
 * ProgramsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramsRepository extends \Doctrine\ORM\EntityRepository
{
}
