<?php

namespace AppBundle\Repository;

/**
 * ProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramRepository extends \Doctrine\ORM\EntityRepository
{
}
