<?php

namespace AppBundle\Repository;

/**
 * RegionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionsRepository extends \Doctrine\ORM\EntityRepository
{
}
