<?php

namespace AppBundle\Repository;

/**
 * SpotTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
