# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.report_helpers:
    class:     AppBundle\Helpers\ReportHelpers
    arguments: ['@doctrine.orm.default_entity_manager']
  app.invoice_data_helpers:
    class:     AppBundle\Helpers\InvoiceDataHelpers
    arguments:
  app.invoice_helpers:
    class:     AppBundle\Helpers\InvoiceHelpers
    arguments: ['@app.invoice_data_helpers']